spring:
  application:
    name: shoot
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
server:
  port: ${APP_PORT:8080}
logging:
  level:
    root: info
    javax.management.remote.rmi: info
    sun.rmi.transport.tcp: info
    sun.rmi.loader: info
    web: debug
    kafka: debug
application:
  shooters:
    save_dir: c:/tmp/save_data/files
    kafkalocal:
      topic: pprs_product_migrator_in
